# Generated by Django 3.2 on 2021-08-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Lamp1',
            },
        ),
        migrations.CreateModel(
            name='tb10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'CCTV_Camera',
            },
        ),
        migrations.CreateModel(
            name='tb2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Lamp2',
            },
        ),
        migrations.CreateModel(
            name='tb3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Lamp3',
            },
        ),
        migrations.CreateModel(
            name='tb4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Lamp4',
            },
        ),
        migrations.CreateModel(
            name='tb5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Lamp5',
            },
        ),
        migrations.CreateModel(
            name='tb6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Air_Conditioner',
            },
        ),
        migrations.CreateModel(
            name='tb7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Door1',
            },
        ),
        migrations.CreateModel(
            name='tb8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Car_Garage',
            },
        ),
        migrations.CreateModel(
            name='tb9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField()),
            ],
            options={
                'db_table': 'Door2',
            },
        ),
    ]
